INSERT INTO ADDRESS(ID, STREETNAME, STREETNUMBER, POSTALCODE, CITY, COUNTRY) VALUES
(1, 'MOZART', '11A', 20037,'MILANO', 'ITALIA');

INSERT INTO PERSON(ID, NAME, SURNAME, MAIL, ADDRESS_ID) VALUES
(1, 'MARIO', 'ROSSI', 'MARIO.ROSSI@MAIL.IT', 1);

INSERT INTO POST(ID, TEXT, PERSON_ID) VALUES
(1, 'CIAO A TUTTI', 1),
(2, 'ARRIVEDERCI A TUTTI', 1);

INSERT INTO HASHTAG(ID, NAME, LINK) VALUES
(1, '#PIZZA', 'URLPIZZA'),
(2, '#PASTA', 'URLPASTA');

INSERT INTO POST_HASHTAG(POST_ID, HASHTAG_ID) VALUES
(1,1),
(1,2),
(2,1),
(2,2);
